version: "3.8"
services:
  backend:
    image: "183184149859.dkr.ecr.eu-west-1.amazonaws.com/reactdemojava:20.1.2023.12.18.10"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev