version: "3.8"
services:
  backend:
    image: "public.ecr.aws/s7t8x3a2/reactdemojava:19.1.2023.14.38.29"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev